repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
        exclude: REQUIREMENTS\.md$
    -   id: end-of-file-fixer
        exclude: REQUIREMENTS\.md$
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: check-yaml
        files: .*\.(yaml|yml)$

-   repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
    -   id: shellcheck
        files: ^shell/

-   repo: local
    hooks:
    -   id: detect-secrets
        name: detect-secrets
        entry: scripts/detect_secrets_baseline.sh
        language: script
        pass_filenames: false
